// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhwnupntkjezgsejdegq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJod251cG50a2plemdzZWpkZWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODM3ODEsImV4cCI6MjA2ODU1OTc4MX0.q062EpAAS6UXb4QQuNdczMnRS4V97gYqoaEObbCDDlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});